name: coffeematch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - streamlit>=1.18
  - altair>=4.2,<5
  - pandas
  - openpyxl
  - numpy
  - dash
  - flask
  - werkzeug
  - pip
  - pip:
      - dash-bootstrap-components

