name: streamlit_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - altair=6.0.0
  - asttokens=3.0.1
  - attrs=25.4.0
  - aws-c-auth=0.9.6
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.2
  - aws-c-event-stream=0.5.9
  - aws-c-http=0.10.10
  - aws-c-io=0.26.1
  - aws-c-mqtt=0.14.0
  - aws-c-s3=0.11.5
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.10
  - aws-crt-cpp=0.37.2
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.2
  - azure-identity-cpp=1.13.3
  - azure-storage-blobs-cpp=12.16.0
  - azure-storage-common-cpp=12.12.0
  - azure-storage-files-datalake-cpp=12.14.0
  - backports.zstd=1.3.0
  - blinker=1.9.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cachetools=6.2.6
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.14.3
  - debugpy=1.8.20
  - decorator=5.2.1
  - emoji=2.15.0
  - et_xmlfile=2.0.0
  - executing=2.2.1
  - gitdb=4.0.12
  - gitpython=3.1.46
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.2.0
  - ipython=9.10.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - krb5=1.22.2
  - lcms2=2.18
  - lerc=4.0.0
  - libabseil=20260107.1
  - libarrow=23.0.1
  - libarrow-acero=23.0.1
  - libarrow-compute=23.0.1
  - libarrow-dataset=23.0.1
  - libarrow-substrait=23.0.1
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcurl=8.18.0
  - libdeflate=1.25
  - libevent=2.1.12
  - libexpat=2.7.4
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.78.0
  - libhwloc=2.12.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libmpdec=4.0.0
  - libparquet=23.0.1
  - libpng=1.6.55
  - libprotobuf=6.33.5
  - libre2-11=2025.11.05
  - libsodium=1.0.18
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.3
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - lz4-c=1.10.0
  - markupsafe=3.0.3
  - matplotlib-inline=0.2.1
  - mkl=2025.3.0
  - narwhals=2.16.0
  - nest-asyncio=1.6.0
  - numpy=2.4.2
  - openjpeg=2.5.4
  - openpyxl=3.1.5
  - openssl=3.6.1
  - orc=2.2.2
  - packaging=26.0
  - pandas=2.3.3
  - parso=0.8.6
  - pillow=12.1.1
  - pip=26.0.1
  - platformdirs=4.9.2
  - prompt-toolkit=3.0.52
  - protobuf=6.33.5
  - psutil=7.2.2
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pyarrow-core=23.0.1
  - pydeck=0.9.1
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.14.3
  - python-dateutil=2.9.0.post0
  - python-gil=3.14.3
  - python-tzdata=2025.3
  - python_abi=3.14
  - pytz=2025.2
  - pywin32=311
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - re2=2025.11.05
  - referencing=0.37.0
  - requests=2.32.5
  - rpds-py=0.30.0
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.2
  - stack_data=0.6.3
  - streamlit=1.54.0
  - tbb=2022.3.0
  - tenacity=9.1.4
  - tk=8.6.13
  - toml=0.10.2
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - ucrt=10.0.26100.0
  - urllib3=2.6.3
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - watchdog=6.0.0
  - wcwidth=0.6.0
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib-ng=2.3.3
  - zstd=1.5.7
  - pip:
      - pyarrow==23.0.1

