name: coffeematch-v1.0
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12

  # Shared libraries
  - pandas
  - numpy
  - openpyxl
  - emoji

  # Streamlit stack
  - streamlit>=1.18
  - altair>=4.2,<5

  # Dash stack
  - dash
  - flask
  - werkzeug
  - pip
  - pip:
      - dash-bootstrap-components

